version: '3.8'

services:
  gestao-contribuintes-api:
    image: gestao-contribuintes-api
    container_name: meu-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/contribuintes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postsenha
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=contribuintes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postsenha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
