version: "3"

services:
  local-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postsenha"
    ports:
      - "7777:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
  
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6666:8080"
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge