version: '3.8'

services:
  db_rpps:
    container_name: db_rpps
    image: postgres:16.2
    environment:
      POSTGRES_DB: db_rpps
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postsenha
    ports:
      - "5434:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db_rpps
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_rpps:5434/db_rpps
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postsenha
    ports:
      - "8081:8080"

volumes:
  postgres-data:
